global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
 level: ERROR
 format: common
 filePath: /var/log/traefik/traefik.log

accessLog:
  format: json
  filePath: /var/log/traefik/access.log

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false

## SSL Options are commented out as SSL will be handled by Cloudflare tunnels
## If needed you can configure the below template to suite your needs

## -- Configure your CertificateResolver here...
# certificatesResolvers:
#   production:
#     acme:
#       email: '`{{env "CF_EMAIL"}}`'
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       dnsChallenge:
#         provider: cloudflare
#         resolvers:
#           - "1.1.1.1:53"
#           - "8.8.8.8:53"

# -- (Optional) Disable TLS Cert verification check
# serversTransport:
#   insecureSkipVerify: true

# -- (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# -- (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12
