version: "3"
name: "protected_infra"

volumes:
  dockersocket:
    external: true
    name: "dockersocket"

  letsencrypt:
    external: true
    name: "letsencrypt"

  backup:
    external: true
    name: "backup"

networks:
  network_vlan:
    external: true
    name: "protected_vlan"

  stack_vlan:
    name: "protected_infra"
    driver: ipvlan

services:

  cfd:
    image: "cloudflare/cloudflared"
    container_name: "protected_infra_cfd"
    hostname: "cfd.protected.local"
    command: tunnel run
    labels:
      com.cfd.infra.protected.description: "Creates a tunnel to the cloudflare to expose services to the internet securely"
      com.cfd.infra.protected.justification: "Ease of use and added security when exposing services to the internet"
    restart: unless-stopped
    privileged: false
    env_file:
      - $SECRETS_DIR/protected/infra/cfd.env
    networks:
      - network_vlan
      - stack_vlan
    cpu_count: 1
    cpu_percent: "100%"
    cpu_shares: 1
    cpu_period: 1
    cpu_quota: 1
    cpu_rt_runtime: 1
    cpu_rt_period: 1
    cpuset: 1
    mem_limit: 512m
