version: "3"
name: "private_infra"

volumes:
  dockersocket:
    external: true
    name: "dockersocket"

  letsencrypt:
    external: true
    name: "letsencrypt"

  backup:
    external: true
    name: "backup"

networks:
  network_vlan:
    external: true
    name: "private_vlan"

  stack_vlan:
    name: "private_infra_vlan"
    driver: ipvlan

services:
  cfd:
    image: "cloudflare/cloudflared"
    container_name: "private_infra_cfd"
    hostname: "cfd.private.local"
    command: tunnel run
    labels:
      com.cfd.infra.private.description: "Creates a tunnel to the cloudflare to expose services to the internet securely"
      com.cfd.infra.private.justification: "Ease of use and added security when exposing services to the internet"
    restart: unless-stopped
    privileged: false
    env_file:
      - $SECRETS_DIR/private/infra/cfd.env
    networks:
      - network_vlan
      - stack_vlan
    cpu_count: 1
    cpu_percent: "100%"
    cpu_shares: 1
    cpu_period: 1
    cpu_quota: 1
    cpu_rt_runtime: 1
    cpu_rt_period: 1
    cpuset: 1
    mem_limit: 512m

  portainer:
    image: "portainer/portainer-ee"
    container_name: "private_infra_portainer"
    domainname: "portainer.$PRIMARY_DOMAIN"
    hostname: "portainer.private.local"
    depends_on:
      - cfd
    labels:
      com.portainer.infra.private.description: "Gives you a UI to easily manage and monitor the docker stacks services"
      com.portainer.infra.private.justification: "A Warpper to enable admins to quickly deploy services and containers"
    restart: always
    privileged: false
    environment:
      - VARIABLE_FILE: /run/secrets/secret_file
    configs:
      file: "../configs/portainer_config.json"
    env_file:
      - $SECRETS_DIR/private/infra/portainer.env
    volumes: 
      - dockersocket:/var/run/docker.sock
      - $DATA_DIR/private/infra/portainer:/data
    expose:
      - "9443"
    networks:
      - network_vlan
      - stack_vlan
    cpu_count: 1
    cpu_percent: "100%"
    cpu_shares: 1
    cpu_period: 1
    cpu_quota: 1
    cpu_rt_runtime: 1
    cpu_rt_period: 1
    cpuset: 1
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "portainer.$PRIMARY_DOMAIN"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
