version: "3"
name: "public_infra"

volumes:
  letsencrypt:
    external: true
    name: "letsencrypt"

  backup:
    external: true
    name: "backup"

networks:
  network_vlan:
    external: true
    name: "public_vlan"

  stack_vlan:
    name: "public_infra"

  cfd_public_connector:
    name: "public_infra_cfd_connector"

services:

  cfd:
    image: "cloudflare/cloudflared"
    container_name: "public_infra_cfd"
    hostname: "cfd.public.local"
    command: tunnel run
    labels:
      com.cfd.infra.public.description: "Creates a tunnel to the cloudflare to expose services to the internet securely"
      com.cfd.infra.public.justification: "Ease of use and added security when exposing services to the internet"
    restart: unless-stopped
    privileged: false
    env_file:
      - $SECRETS_DIR/public/infra/cfd.env
    networks:
      - network_vlan
      - stack_vlan
      - cfd_public_connector
    cpu_count: 1
    mem_limit: 512m
