name: "Release to the server on merge to master"

run-name: "release"

on: workflow_dispatch
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  login:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    steps:
      - name: "Login to the server and run commands"
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ${{ secrets.PATH }}
            git pull
            sudo sh run.sh &>> "logs/main-$(date+'%Y-%m-%d').log"
        env:
          CI: true
