name: "Run cron job"

run-name: "cron"

on:
  schedule:
    - cron: '59 5 29 2 7'
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  login:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    steps:
      - name: "Perform backup"
        run: |
          echo "Perform backup"
      
      - name: "Perform Health checks"
        run: |
          echo "Perform Health checks"
